### PR TITLE
malloc/free implementation

### LINKED ISSUE #654: Implementation of malloc is missing
**Describe the bug**

During the development of https://github.com/tweag/asterius/issues/639, I noticed that the nofib test [`shootout/n-body`](https://gitlab.haskell.org/ghc/nofib/-/blob/master/shootout/n-body/Main.hs) fails with
```
Main: JSException "RuntimeError: barf: malloc    
    at ExceptionHelper.barf (file:///home/skull/tweag/asterius-alt/asterius/nofib/shootout/n-body/rts.exception.mjs:147:13)    
    at barf (wasm-function[132]:0x7747)    
    at Main_.Lc8NO (wasm-function[41]:0x3ff5)    
    at scheduleTSO (wasm-function[4107]:0xd99a4)    
    at scheduleTSO_wrapper (wasm-function[4108]:0xd99d1)    
    at Scheduler.tick (file:///home/skull/tweag/asterius-alt/asterius/nofib/shootout/n-body/rts.scheduler.mjs:346:22)    
    at Immediate.<anonymous> (file:///home/skull/tweag/asterius-alt/asterius/nofib/shootout/n-body/rts.scheduler.mjs:381:29)    
    at processImmediate (internal/timers.js:456:21)"
```

This probably means that we have no working implementation of `malloc` for node to use.

**To Reproduce**
Download `Main.hs` from [here](https://gitlab.haskell.org/ghc/nofib/-/blob/master/shootout/n-body/Main.hs), build it with Asterius, and execute using node:
```
ahc-link  --ghc-option=-O2 --ghc-option=-Rghc-timing --ghc-option=-H32m --ghc-option=-rtsopts --ghc-option=-fexcess-precision --verbose-err --input-hs Main.hs
node Main.mjs 500000
```

**Expected behavior**
The program should execute without errors. The expected stdout can be found [here](https://gitlab.haskell.org/ghc/nofib/-/blob/master/shootout/n-body/n-body.faststdout).

**Environment**
* OS name + version: Ubuntu 18.04.4 LTS (bionic)
* GHC version: 8.8.3
* Cabal version: 3.2.0.0
* Version of Asterius: 42d5be0b806211daf627aa6e16f65102bf3c06b0

### PR DESCRIPTION
**Pull request by TerrorJack**
Closes #654.

This should suffice to get stuff working before #658 lands. This implementation allocates one pinned `ByteArray#` for each `malloc` call, sets up a `StablePtr#` for the `ByteArray#` closure, and store the `StablePtr#` in the payload's first word. Starting from the second word of the payload is available space as the result of `malloc`. `free` would simply fetch the `StablePtr#` and free it, so later the garbage collector would be able to recycle the space taken by `ByteArray#`.

### CODE REVIEW

File: asterius/src/Asterius/Builtins/Malloc.hs [hunk 1]
```diff
@@ -0,0 +1,41 @@
+{-# LANGUAGE OverloadedStrings #-}
+
```
Comment (gkaracha) [inline asterius/src/Asterius/Builtins/Malloc.hs:2]: Since the strategy has its intricacies, I'd put your PR description in the file so that we don't forget:
```suggestion

-- |
-- Module      :  Asterius.Builtins.Malloc
-- Copyright   :  (c) 2018 EURL Tweag
-- License     :  All rights reserved (see LICENCE file in the distribution).
--
-- Wasm implementations of @malloc@ and @free@. This implementation of
-- @malloc@/@free@ allocates one pinned @ByteArray#@ for each @malloc@ call,
-- sets up a @StablePtr#@ for the @ByteArray#@ closure, and stores the
-- @StablePtr#@ in the payload's first word. Hence, the available space as the
-- result of @malloc@ starts from the second word of the payload. Conversely,
-- @free@ fetches the @StablePtr#@, subtracts the size of a word (to account
-- for the additional first word), and and frees it, so that the garbage
-- collector can later recycle the space taken by the @ByteArray#@.
```

File: asterius/src/Asterius/Builtins/Malloc.hs [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+  sp <- call' "getStablePtr" [c] I64
+  storeI64 c offset_StgArrBytes_payload sp
+  emit $ c `addInt64` constI64 (offset_StgArrBytes_payload + 8)
+
+free :: AsteriusModule
+free = runEDSL "free" $ do
+  p <- param I64
+  call "freeStablePtr" [loadI64 (p `subInt64` constI64 8) 0]
+
+roundup_bytes_to_words_expr :: Expression -> Expression
```
Comment (gkaracha) [inline asterius/src/Asterius/Builtins/Malloc.hs:39]: I know that `roundup_bytes_to_words_expr` is not exported, but by convention I'd use camelCase anyway (`roundupBytesToWordsExpr`), since it's a top-level function .
